### ISSUE TITLE
Contact button at the footer doesn't work properly.

### ISSUE THREAD

**Issue by celkacelka** [rotki/rotki.com#14]
Pressing Contact for the first time opens the popup asking what you want to open it with. Choosing a browser opens an empty tab. It's due to mailto functionality, which only makes sense for users of Outlook and such.
Another solution would be a Contact page with 3 fields: Name, Email address, Message. All messages should be then directed to info@rotki.com.

**Comment by kelsos** [comment]
At least on firefox you can also configure mailto: to open gmail
![image](https://user-images.githubusercontent.com/2269732/159012313-ff375072-6101-422a-904d-9a5c6be6f333.png)

**Comment by cleanerzkp** [comment]
I've tested the contact button in the footer, and I can confirm that it's now working correctly. When clicked, it opens the default mail application and populates the recipient field with info@rotki.com.

Given that the functionality is now working as expected, I suggest we close this issue.

**Comment by kelsos** [comment]
If I recall correctly when we discussed the issue, we concluded that the form approach would require a lot of work, just to avoid people using the form to send spam, and we decided that we will not spend resources on it.

I am gonna close the issue for the time being.
