### ISSUE TITLE
Update landing page to the new design

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki.com#152]
## Description

Update the landing to the new [design](https://www.figma.com/file/msxmKajRPLYiDDmsP60Ndh/Design-System-v1.1?type=design&node-id=1631-87997&mode=design&t=B67pOBnsn3sk9m3s-0).

From the following section at the moment we need only the free and basic (which will be named premium) and skill feature table below

![image](https://github.com/rotki/rotki.com/assets/2269732/9161129e-281f-48f0-8a9d-9275247e4aa4)

> *About the user comments*: make sure that we make it dynamic similar to jobs section so that we can update without the need to deploy.
 

## Tasks
- [ ] Implement new landing page

**Comment by vinuch** [comment]
hi @kelsos can i work on this ?

**Comment by kelsos** [comment]
hey @vinuch we will handle this internally.

**Comment by vinuch** [comment]
no problem @kelsos! 

By any chance are there frontend issues that you wouldn't mind external contribution on? I am quite interested in the project, I have it setup locally and everything and I would love to contribute. if there are, do point me in that direction thanks.

keep up the great work y'all are doing 🙌🏽

**Comment by kelsos** [comment]
This was closed by #165

**Comment by kelsos** [comment]
> no problem @kelsos!
> 
> By any chance are there frontend issues that you wouldn't mind external contribution on? I am quite interested in the project, I have it setup locally and everything and I would love to contribute. if there are, do point me in that direction thanks.
> 
> keep up the great work y'all are doing 🙌🏽

Hey @vinuch hmm check the app repo there might be stuff there :)
