### ISSUE TITLE
Introduce ability to resent the activation e-mail

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki.com#170]
## Description

When the alert showing that your address has been verified is visible a button need to be added to re-send the verification e-mail

@yabirgb can we fill the endpoint and any more schema related information here?

**Comment by yabirgb** [comment]
Endpoint: `webapi/email-verification/`
Verb: `GET`

Will fail with code `UNAUTHORIZED` if not enough time has passed since the last request. Message

```
{"message": "You have to wait {datetime.timedelta(seconds=time_until_resend)} before requesting a new verification code"}
```

In success:

```
{"result": true}
```
status code: `OK`
