### ISSUE TITLE
Add supported Cexes, DeFi protocols in the website's frontpage.

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki.com#29]
## Abstract

It's currently hard for a prospective user to figure out which Cexes, dexes, defi protocols (portfolio tracking), defi protocols(historic accounting) do we support. Example feedback: https://twitter.com/scott_lew_is/status/1294768587769548805

## Task

Add these information on the website and possibly also on the readme of this github repo.

**Comment by kelsos** [comment]
So we need to add or update any sections related to this on the product details and provide a link to each section from the landing page.
