### ISSUE TITLE
Specify that stable coin and ETH payments are on ethereum main net

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki.com#46]
## Requirement

Add a note that the payments using ETH or stablecoins is on ethereum mainnet

**Comment by LefterisJP** [comment]
The what mainnet? :rofl:

**Comment by kelsos** [comment]
> The what mainnet? 🤣
I am pretty sure that was auto-corrected 😛

**Comment by kelsos** [comment]
I am closing this since we are going to add the side-chains/l2s so it would be quite clear what chain the payment is going to
