### ISSUE TITLE
Make payment provider error more obvious

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki.com#73]
**Describe the bug**

The payment provider error is at the same weight and font-style as the rest of the message.

![image](https://user-images.githubusercontent.com/2269732/227185194-6c7f4c78-f56f-4eca-b96d-31286d39490c.png)

Change it so that the error message is highlighted. (maybe medium/bold weight?)

**Comment by tewshi** [comment]
<img width="1093" alt="Screenshot 2023-04-13 at 11 24 43" src="https://user-images.githubusercontent.com/5625068/231732991-15df986f-42ca-4a62-9425-d30f72648859.png">

@kelsos if this is okay, slightly bigger font, medium.
