### ISSUE TITLE
Provide visual feedback when account information is updated

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki.com#74]
## Description

At the moment you can see the button loading but there is not visual confirmation on a successful save of the account information

## Requirements

Add a success indicator (check icon?) next to the button along with a success message.
The message appears after a successful save and auto-hides after some time (5-6 seconds?)

**Comment by kelsos** [comment]
Hey @tewshi @lukicenturi do you think we have covered what this issue describes?

**Comment by lukicenturi** [comment]
I can pick it

**Comment by lukicenturi** [comment]
<img width="1022" alt="image" src="https://github.com/rotki/rotki.com/assets/26648140/db43f821-6656-4d0f-a0bf-8f395e124f25">
The issue created before the web revamp right? 
Now we have small notification right this
